### ISSUE TITLE
Kapitelseite: Filterfunktion korrigieren

### ISSUE THREAD

**Issue by SimonneBosiers** [mynimi/csr-lateinamerika#25]
[website_feedback_sbo_20180116_filter.pdf](https://github.com/mynimi/csr-lateinamerika/files/1636856/website_feedback_sbo_20180116_filter.pdf)

**Comment by DamianSchurtenberger** [comment]
Analog Vorschlag von Damian mit Anpassungen von Simone Bosiers umsetzen
